title: USPdev
#email: @usp.br
description: Grupo de desenvolvedores da Universidade de São Paulo 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://uspdev.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
